Repository jenkinsci/junit-realtime-test-reporter-plugin, pull requests merged in 2021-12, with the labels that each got.

#12 Build result based on the current step results
  pom.xml
  src/main/java/org/jenkinsci/plugins/junitrealtimetestreporter/MavenAttacher.java
  src/main/java/org/jenkinsci/plugins/junitrealtimetestreporter/RealtimeJUnitStep.java
  src/test/java/org/jenkinsci/plugins/junitrealtimetestreporter/RealtimeJUnitStepTest.java
Labels: enhancement

#14 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .gitignore
  .mvn/extensions.xml
  .mvn/maven.config
  LICENSE.md
  README.md
  pom.xml
Labels: chore

#19 Add override for #getFailedTests()
  src/main/java/org/jenkinsci/plugins/junitrealtimetestreporter/AbstractRealtimeTestResultAction.java
Labels: enhancement

#18 Pass task listener to JUnit parsing
  README.md
  pom.xml
  src/main/java/org/jenkinsci/plugins/junitrealtimetestreporter/PipelineRealtimeTestResultAction.java
  src/main/java/org/jenkinsci/plugins/junitrealtimetestreporter/RealtimeJUnitStep.java
  src/main/resources/org/jenkinsci/plugins/junitrealtimetestreporter/Messages.properties
Labels: bug

#25 Use single quotes for pipeline example
  README.md
Labels: documentation
